spring:
  application:
    name: api-gateway
  cloud:    gateway:      discovery:        locator:          enabled: true          lower-case-service-id: true      routes:      - id: course-service
        uri: lb://course-service        predicates:        - Path=/api/course    loadbalancer:      ribbon:        enabled: false
eureka:  instance:    instance-id: ${spring.application.name}:${random.uuid}