package com.dtw.commons.enums;

public enum ReturnStatus {

	ENTITY_NOT_FOUND,
	USER_NOT_FOUND,
	COURSE_NOT_FOUND,
	ASSIGNMENT_NOT_FOUND,
	HOMEWORK_NOT_FOUND,
	
	ENTITY_DOESNT_CONTAIN_ENTITY,
	COURSE_DOESNT_CONTAIN_ASSIGNMENT,
	COURSE_DOESNT_CONTAIN_USER,
	COURSE_DOESNT_CONTAIN_TEACHER,
	COURSE_DOESNT_CONTAIN_STUDENT,
	ASSIGNMENT_DOESNT_CONTAIN_HOMEWORK,
	
	ENTITY_ALREADY_CONTAINS_ENTITY,
	
	ENTITY_WITH_IDENTIFIER_ALREADY_EXISTS,
	ENTITY_WITH_EMAIL_ALREADY_EXISTS,
	ENTITY_WITH_USERNAME_ALREADY_EXISTS,
	
	OK,
	FORBIDDEN
}