server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true  application:    name: course-service
eureka:  instance:    instance-id: ${spring.application.name}:${random.uuid}