server:
  port: 8080
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - DELETE
            - PUT
            - PATCH
            - OPTIONS
      routes:
      - id: course-service
        uri: lb://course-service
        predicates:
        - Path=/api/course/**
      - id: assignment-service
        uri: lb://assignment-service
        predicates:
        - Path=/api/assignment/**
      - id: homework-service
        uri: lb://homework-service
        predicates:
        - Path=/api/homework/**
      - id: course-aggregator-service
        uri: lb://course-aggregator-service
        predicates:
        - Path=/api/courseAggregator/**
      - id: auth-server
        uri: lb://auth-server
        predicates:
        - Path=/oauth/**
      - id: webapp
        uri: http://localhost:4200/**
        predicates:
        - Path=/web/**
    discovery:
      enabled: true
  application:
    name: gateway-service
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true