server:
  port: 8080
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - DELETE
            - PUT
            - PATCH
            - OPTIONS
      routes:
      - id: course-service
        uri: lb://course-service
        predicates:
        - Path=/api/course/**
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/api/user/**
      - id: webapp
        uri: http://localhost:4200/**
        predicates:
        - Path=/web/**
    discovery:
      enabled: true
  application:
    name: gateway-service
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true